### ISSUE TITLE
A Bug with your Direct Downloads plugin

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Inve1951/BetterDiscordStuff#108]
### First of all: 
Why aren't these on The Better Discord Site? Literally everyone would be using these if they were.

### The Bugs: 
After downloading something sometimes they won't show in the folder. Also, direct downloads for Better Discord themes or just something from the better discord site will not download.

### Suggestions: 
Please add a choose file path option for Direct Downloads.

**Comment by ZaneDragonBorn** [comment]
Also, your Highlight self plugin does nothing

**Comment by Inve1951** [comment]
Hi, and thanks for filing this issue.

> Why aren't these on The Better Discord Site? Literally everyone would be using these if they were.

Currently the only official source of plugins are the 2 Discord servers. The current maintainers of BD lack the necessary access to make changes to http://betterdiscord.net/. There are plans to provide in-client browsable plugin and theme repositories.

> After downloading something sometimes they won't show in the folder.

That's a first. Please check your console (`ctrl+shift+I`) to see whether an error occurred. If that's the case, please share it's details here. If there's no error logs then potentially your AV software has removed the files right after they've been written to disk.

> Also, direct downloads for Better Discord themes or just something from the better discord site will not download.

This is a known issue with Cloudflare's DDOS protection. Instead of the actual plugin/theme file the webserver returns an HTML document which does some magic before performing a redirect initiated by the client.

While the plugin *could* work around that by opening the link in an invisible browser window and intercepting the redirect, the best solution here would be for the website to whitelist download links. Unfortunately I haven't been able to get into contact with it's owner.

> Please add a choose file path option for Direct Downloads.

This actually is already implemented but a bug in Electron prevents it from operating. When clicking the button showing your current download location in the plugin's settings, an OS-native *folder-select* dialog is supposed to appear.

Tho if I remember correctly then a workaround is already in place and it should function normally. If not, then that workaround is in `LocalFileServer`. PRs welcome.
