### ISSUE TITLE
deafult to emoji breaks LINE stickers plugin

### ISSUE THREAD

**Issue by Psycho-Hedgie** [Inve1951/BetterDiscordStuff#18]
This isn't your fault. Plugins can interfere with a lot of other plugins and themes. 
I don't blame you if you don't wanna fix this. The UI is fine but when you select a LINE sticker with your plugin enabled, it'll fail to type the sticker url 
https://github.com/awaken1ng/bd-linestickers

**Comment by Inve1951** [comment]
can't really be my plugin's doing, because all it does is clicking the emojis button in the picker when it opens.

btw that linesticker plugin is inofficial, i don't know the author and never heared of the plugin before.
also just had a quick look at it's source code and saw a lot of manipulating the default picker.
i suggest you ask the lineemotes author to have a look.
