### ISSUE TITLE
botInfo doesnt works

### ISSUE THREAD

**Issue by nitrog0d** [Inve1951/BetterDiscordStuff#20]
I don't know how it's supposed to work, but it's not working, when I open any Bot profile from Discord Bots List nothing happens...

**Comment by Inve1951** [comment]
I am aware of this issue and there's currently no clean solution to it.
Discord had some behind the scenes changes where instead of using `React.createElement` they create their elements manually for some components thruout discord. BotInfo is the first and only plugin affected by this up until now.

**Comment by Ryonez** [comment]
Might pay to update the plugin info to reflect this. It's not clear to new users downloading it currently.

**Comment by Inve1951** [comment]
you gonna pay me to do that?

**Comment by Ryonez** [comment]
Not with that attitude I won't be.

Besides, you're the one currently offering something that isn't functioning.

I'm not saying it's trash or anything, I haven't even looked at the code. But if you know it's not going to work due to something outside of your power to fix atm, make that clear to people before they download it is all.

**Comment by NFLD99** [comment]
+Ryonez just because something is broken doesn't mean it needs a discamer, discord it's self is broken as fuck for fuck sakes

**Comment by Inve1951** [comment]
i just find it's a weird thing to pay for. especially with (close to) nobody even reading the readme here.

**Comment by Inve1951** [comment]
fixed in 44785f4fe1ffb5b512e561b6d62a2663a84e1ac5
