### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of null (Bot Info)

### ISSUE THREAD

**Issue by TheEssemCraft** [Inve1951/BetterDiscordStuff#39]
I get this error in the console with the Bot Info script:
```
Uncaught TypeError: Cannot read property 'constructor' of null
    at MutationObserver.<anonymous> (C:\Users\redhe\AppData\Roaming\BetterDiscord\plugins\botInfo.plugin.js:108:74)
```
This causes it to stop working. Any fixes?

**Comment by Inve1951** [comment]
Thanks for reporting. Yes that seems to be the reason. i'll look into it.

**Comment by Inve1951** [comment]
I just fixed the plugin and I'm sorry to say, it's dead.
While the plugin is theoretically fully functional again it seems that [discordbots.org](https://discordbots.org/api/docs#reference) changed their API to require an authentication token, which is not an option for an entirely open-sourced project.
I was about to ask them how to proceed but seemingly they require me to link my private phone number to my discord account in order to use their chat. I'm most certainly not gonna do that.
